### ISSUE TITLE
Admin dashboard ?

### ISSUE THREAD

**Issue by pragmatech** [KumailP/kumails-blog#4]
Hi. Cool project. Thanks for sharing.
Is the netlify cms admin not available,
or am I overlooking something?

**Comment by KumailP** [comment]
Hey @pragmatech , the CMS Admin dashboard is at https://kumailp.com/admin

**Comment by pragmatech** [comment]
thanks! 
I'm having a "duh!"-moment, i.e., I need to deploy to Netlify before I can access the admin dashboard, right?

**Comment by KumailP** [comment]
@pragmatech I think thats right, you might not be able to access it locally and need to deploy it first
